# Numpy 기초연습문제

In [1]:
import numpy as np

### 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.

In [2]:
#zeros는 0으로 가득 찬 array를 생성
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.

In [3]:
#행렬의 차원을 shape라는 개념으로 표현
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] = i*4 + j + 1  
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [4]:
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num
        num += 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [5]:
a[1, 2]

7.0

### 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

In [6]:
a.shape

(3, 4)

In [7]:
a[[1], :]

array([[5., 6., 7., 8.]])

### 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.

In [8]:
a[:,[0, 2]]

array([[ 1.,  3.],
       [ 5.,  7.],
       [ 9., 11.]])

### 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오.

In [9]:

result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result

array([1., 2., 3., 4., 5., 6.])

In [10]:
a[a <= 6]

array([1., 2., 3., 4., 5., 6.])

### 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.

In [11]:
b = np.random.random((3, 4))
b

array([[0.35623121, 0.29698542, 0.17113545, 0.98597294],
       [0.08369702, 0.04015219, 0.40925171, 0.77203309],
       [0.27532366, 0.19191228, 0.19886757, 0.33240595]])

### 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [12]:
c = a * b
c

array([[0.35623121, 0.59397083, 0.51340634, 3.94389176],
       [0.41848509, 0.24091312, 2.864762  , 6.17626469],
       [2.47791293, 1.91912284, 2.18754332, 3.98887143]])

### 9. b의 전치행렬을 구하여 d에 저장하시오.

In [13]:
d = b.T
d

array([[0.35623121, 0.08369702, 0.27532366],
       [0.29698542, 0.04015219, 0.19191228],
       [0.17113545, 0.40925171, 0.19886757],
       [0.98597294, 0.77203309, 0.33240595]])

In [14]:
d.shape

(4, 3)

### 10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [15]:
print(a.shape, d.shape)

(3, 4) (4, 3)


### 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.

In [16]:
#dot 행렬곱
e = a.dot(d)
e

array([[ 5.40750013,  4.47988888,  2.58537476],
       [12.64880017,  9.70042489,  6.57941265],
       [19.8901002 , 14.92096091, 10.57345053]])

### 12. e에 대하여 각 열의 합을 계산하시오.

In [18]:
np.sum(e, axis=1)

array([12.47276377, 28.92863771, 45.38451164])